CREATE TABLE Sellers
(
	SellerId INT IDENTITY NOT NULL PRIMARY KEY,
	SellerName NVARCHAR(40) NOT NULL,
	Phone NVARCHAR(20) NOT NULL
)
GO
CREATE TABLE Products
(
	ProductId INT IDENTITY PRIMARY KEY,
	ProductName NVARCHAR(40)  NOT NULL,
	Price MONEY NOT NULL,
	MfgDate DATE NOT NULL,
	InStock BIT,
	Picture NVARCHAR(40) NOT NULL,
)
go
CREATE TABLE Sales
(
	SalesId INT IDENTITY PRIMARY KEY,
	[Date] DATE NOT NULL,
	SellerId INT NOT NULL REFERENCES Sellers(SellerId),
	Quantity INT NOT NULL,
	ProductId INT NOT NULL REFERENCES Products (ProductId)
)
GO